temp_directory: E:/Development/temp_downloads/
google_api_key: 
transit_feed_key: 
# these default tables provides the core of the application, if you need more feel free to add, but read the READ ME first.
tables: 
  - agency
  - feed_info
  - trips
  - calendar_dates
  - routes
  - stop_times
  - stops

# in hour
# f.e: 2:30:00
update_delay_time:
# in days: f.e: 1 <- one day 
update_restart_interval: 1

vaadin:
  compatibilityMode: false
  productionMode: false
  enableDevServer: false