server:
  port: 8090
spring:
  datasource-devel:
   driver-class-name: org.postgresql.Driver 
   jdbcUrl: jdbc:postgresql://localhost:5432/cts-data
   username: postgres
   password: home
   schema: test_gtfs
   separator: ^;
  servlet: 
   multipart:
    max-file-size: 50MB
    max-request-size: 50MB
---
configs:
   websocketServer: ws://localhost:742/cts-app/channel
   threadParams:
      initDelayed: 30
      delayBetween: 40
   tempDirectory: E:/Development/temp_downloads/
   tables:
      - agency
      - feed_info
      - trips
      - calendar_dates
      - routes
      - stop_times
      - stops
      - shapes
      - pathways